services:
  auth:
    build:
      dockerfile: bun.dev.dockerfile
      context: .
    working_dir: /app
    volumes:
      - ..:/app
    command: bun --watch apps/auth/src/main.ts
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: kinglith
      DB_PASS: kinglith
      DB_BASE: kinglith
      DB_PORT: 5432
    ports:
      - '4321:3000'

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: kinglith
      POSTGRES_PASSWORD: kinglith
      POSTGRES_DB: kinglith
    ports:
      - '5555:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kinglith']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
